# Generated by Django 4.2.7 on 2025-08-03 08:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("PHISHING", "Phishing"),
                            ("SPAM", "Spam"),
                            ("MALWARE", "Malware"),
                            ("USB", "USB Activity"),
                            ("NETWORK", "Network"),
                            ("PROCESS", "Process"),
                            ("SYSMON", "Sysmon"),
                            ("SYSTEM", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                ("message", models.TextField()),
                ("source", models.CharField(max_length=100)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("resolved", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ProcessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("process_name", models.CharField(max_length=255)),
                ("process_id", models.IntegerField()),
                ("cpu_percent", models.FloatField()),
                ("memory_percent", models.FloatField()),
                ("command_line", models.TextField(blank=True)),
                ("suspicious", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SystemInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("cpu_percent", models.FloatField()),
                ("memory_percent", models.FloatField()),
                ("disk_usage", models.FloatField()),
                ("network_connections", models.IntegerField()),
                ("active_processes", models.IntegerField()),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
