# Generated by Django 4.2.7 on 2025-08-10 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        (
            "dashboard",
            "0002_memoryanalysis_networktraffic_alter_alert_alert_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "threat_type",
                    models.CharField(
                        choices=[
                            ("MALWARE", "Malware"),
                            ("RANSOMWARE", "Ransomware"),
                            ("NETWORK_ATTACK", "Network Attack"),
                            ("INSIDER_THREAT", "Insider Threat"),
                            ("CREDENTIAL_THEFT", "Credential Theft"),
                            ("PRIVILEGE_ABUSE", "Privilege Abuse"),
                            ("SYSTEM_TAMPERING", "System Tampering"),
                            ("DATA_EXFILTRATION", "Data Exfiltration"),
                            ("UNKNOWN", "Unknown"),
                        ],
                        max_length=50,
                    ),
                ),
                ("raw_data", models.JSONField(default=dict)),
                ("ai_analysis_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("ai_confidence", models.FloatField(default=0.0)),
                ("ai_explanation", models.TextField(blank=True)),
                ("ai_remediation_steps", models.JSONField(blank=True, default=list)),
                ("ai_pattern_insights", models.JSONField(blank=True, default=dict)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("resolution_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "source_alert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="dashboard.alert",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
    ]
